server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_demo
    username: admin
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect